
server:
  port: 8081
spring:
  application:
    name: movie-service
spring:
  datasource:
    url: jdbc:h2:mem:moviesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
